-- SELECT
--     c.name,
--     SUM(od.quantity * p.price) AS revenue
-- FROM customers c
-- JOIN orders o ON c.customer_id=o.customer_id
-- JOIN order_details od ON o.order_id=od.order_id
-- JOIN products p ON od.product_id=p.product_id
-- GROUP BY c.name
-- ORDER BY revenue DESC
-- LIMIT 5;